### ISSUE TITLE
unable to set up captcha: ImportError: No module named client 

### ISSUE THREAD

**Issue by tchncs** [ayleph/mediagoblin-recaptcha#7]
Hi, just wanna note that your nocaptcha branch wont work because

`ImportError: No module named client`

Somehow not possible to match the depends.

**Comment by tchncs** [comment]
As is just saw, it happends with the master branch also, but not on dbupdate, it happends in the live instance. I solved this in the past when i met you in the irc but sadly i just safed the mediagoblin patches and dont remember how i solved this problem.

```
python                                                                                                                                                            completing external command
python            python2           python2.7         python2.7-config  python2-config    python3           python3.4         python3.4m        python3m          python-config
```

```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> require('recaptcha-client')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'require' is not defined
>>> from pkg_resources import require
>>> require('recaptcha-client')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: recaptcha-client
>>> from recaptcha.client import captcha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'recaptcha'
```

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from recaptcha.client import captcha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named recaptcha.client
>>> from pkg_resources import require
>>> require('recaptcha-client')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: recaptcha-client
```
```
 python -c 'from recaptcha.client import captcha'                                                                                                                                                                           :(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named recaptcha.client
```
`recaptcha-client 1.0.6` is installed
`recaptcha 1.0rc1` is installed

**Comment by ayleph** [comment]
I'm not sure what happened here, but it's been working fine for me with recaptcha-client ==1.0.6 from PyPI.

**Comment by zhou0213** [comment]
how did you resolve that?

**Comment by ayleph** [comment]
I didn't have to resolve anything; it just worked for me using recatpcha-client 1.0.6.

```
~/mediagoblin-dev $ bin/pip freeze | grep -i recaptcha
recaptcha-client==1.0.6
~/mediagoblin-dev $ bin/python2 -c 'from recaptcha.client import captcha'
~/mediagoblin-dev $
```

Even if I install the recaptcha package (which isn't needed), it still works. So I can't figure out what caused the problem that @tchncs had. Maybe the issue was not installing recaptcha-client into the mediagoblin virtualenv?

Edit: the readme doesn't explicitly state to install recaptcha-client into the virtualenv, as it assumed that if you were hacking on mediagoblin then you had already activated the virtualenv. Probably a poor assumption. Make sure that you activate the virtualenv before installing the recaptcha-client package, because mediagoblin doesn't use system-wide packages by default.

```
$ cd /path/to/mediagoblin
$ source bin/activate
(mediagoblin) $ pip install recaptcha-client
```

Let me know if that fixes the issue, and I'll update the readme if necessary.

**Comment by thechitowncubs** [comment]
This isn't working on 0.10 and Python3

2021-01-28 20:23:03,464 INFO    [mediagoblin.plugins.recaptcha] Setting up recaptcha...
2021-01-28 20:23:03,465 INFO    [mediagoblin.plugins.recaptcha] Done setting up recaptcha!

I don't see any recaptcha on the login.

https://media.utopiaeducators.com
